version: '3'

services:
  webdriver:
    build: webdriver/
    ports:
      - 4444:4444
    networks:
      - deploy_network
    container_name: webdriver

  elasticsearch:
    build: elasticsearch/
    ports: 
      - 9200:9200
    networks:
      - deploy_network
    container_name: elasticsearch

  helper:
    build: helper/
    volumes:
      - ./helper:/app
    depends_on:
      - elasticsearch
      - webdriver
    networks:
      - deploy_network
    container_name: helper

networks:
  deploy_network:
    driver: bridge