version: '3'

services:
  webdriver:
    build: webdriver/
    ports:
      - 4444:4444
    networks:
      - deploy_network
    container_name: webdriver
    shm_size: '2gb'

  elasticsearch:
    build: elasticsearch/
    ports: 
      - 9200:9200
    networks:
      - deploy_network
    container_name: elasticsearch

  bot:
    build: bot/
    volumes:
      - ./bot:/app
    depends_on:
      - elasticsearch
    networks:
      - deploy_network
    container_name: bot

  crawler:
    build: crawler/
    volumes:
      - ./crawler:/app
    depends_on:
      - elasticsearch
      - webdriver
    networks:
      - deploy_network
    container_name: crawler

networks:
  deploy_network:
    driver: bridge