version: '3'

services:
  elasticsearch:
    build: elasticsearch/
    ports: 
      - 9200:9200
    networks:
      - deploy_network
    container_name: elasticsearch

  helper:
    build: helper/
    volumes:
      - ./helper:/app
    depends_on:
      - elasticsearch
    networks:
      - deploy_network
    container_name: helper

networks:
  deploy_network:
    driver: bridge