# -*- coding: utf-8 -*-

TIPS_LIST = [
    'Always plan your route before the start of the raid.',
    'Never go in raid without an objective.',
    'Never pick a fight you are not sure to win.',
    'Pick the right gear for the right raid.',
    'Never go out without heal, bandage and painkillers on you.',
    'You can\'t hear if you are loud.',
    'Always be suspicious of bushes.',
    'Take your time.',
    'Killa can freeze himself for a second when he is shot. Take advantage.',
    'Always protect your head first from grenades.',
    'Never camp the exit.',
    'Patience is rewarding.',
    'If it is too good to be true, it is probably a trap.',
    'If you don\'t have the biggest gun, have the biggest brain.',
    'Never feel too confident, but never be scared.',
    'Be a ninja.',
    'Never turn your back to a BEAR.',
    'Style is as important as protection.',
    'Always dominate with violence of action.',
    'Sometimes, it is ok to fall back.',
    'The priciest ammo might not be the best ammo.',
    'Grenades can solve complicated situations really fast.',
    'It is all about seeing before being seen.',
    'Don\'t be greedy.',
    'The hideout is a must have investment.',
    'Always insure your belongings.',
    'Don\'t forget to log in to retrieve your insurances returns.',
    'The price that matters is the price per slot.',
    'As a group, always have a leading leader.',
    'Stay frosty.',
    'Keep an eye on the clock.',
    'Think twice before selling that item.',
    'Never speculate on the mayonnaise.',
    'Who drinks bleach, die clean.',
    'If it smells la chignole, brace for the worst.']
